console.log("===================")
console.log(3 === 3.0)
console.log(42 === '42')
console.log(null === null)
console.log(undefined === undefined)
console.log(undefined === null)
console.log(NaN === NaN)
console.log(0 === -0)
console.log(Number.isNaN(NaN), Number.isNaN(-NaN), Number.isNaN(42))
console.log(Object.is(NaN, NaN))
console.log(Object.is(0, -0))
console.log(Object.is(3.0, 3))
console.log(Object.is(42, '42'))
console.log("===================")
console.log(42 == '42')
console.log("" == 0)
console.log(1 == true)
console.log(9 < "10", "9" < "10")
console.log(null == false, [] == false, [] == true, {} == false, {} == true)
if ({}) {
    console.log("kuku")
}
